name: Restrict Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  restrict:
    runs-on: ubuntu-latest
    steps:
      - name: Restrict Pull Request Merges
        uses: fkirc/restrict-pull-request@v1
        with:
          allowed-branches: develop
